# 1 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 2 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_MapScripts::
# 3 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 5 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Woman::
# 6 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
# 7 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 8 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 9 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Cook::
# 10 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
# 11 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 12 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 13 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Man::
# 14 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
# 15 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 17 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring:
# 18 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "¿Entrevistarán hoy a algún ENTRENADOR\n"
# 19 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "de los buenos?$"
# 20 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 21 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere:
# 22 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "Si abriese un restaurante aquí,\n"
# 23 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "seguro que me forraba.$"
# 24 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 25 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles:
# 26 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "¡Uf!…\p"
# 27 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "Necesito tomarme estos descansos\n"
# 28 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "después de unos combates tan duros…\p"
# 29 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "Pero lo que no puedo es dejar de pensar\n"
# 30 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "en estrategias y movimientos.$"
