# 1 "data/maps/RustboroCity_House2/scripts.pory"

# 2 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_MapScripts::
# 3 "data/maps/RustboroCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_House2/scripts.pory"

# 5 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_PokefanF::
# 6 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
# 7 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 8 "data/maps/RustboroCity_House2/scripts.pory"

# 9 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_LittleGirl::
# 10 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
# 11 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 12 "data/maps/RustboroCity_House2/scripts.pory"

# 13 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_TrainerSchoolExcellent:
# 14 "data/maps/RustboroCity_House2/scripts.pory"
	.string "La ESCUELA de ENTRENADORES\n"
# 15 "data/maps/RustboroCity_House2/scripts.pory"
	.string "es excelente.\p"
# 16 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Si estudias allí, es probable que un día\n"
# 17 "data/maps/RustboroCity_House2/scripts.pory"
	.string "llegues a ser LÍDER de GIMNASIO.$"
# 18 "data/maps/RustboroCity_House2/scripts.pory"

# 19 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_RoxanneKnowsALot:
# 20 "data/maps/RustboroCity_House2/scripts.pory"
	.string "PETRA, la LÍDER del GIMNASIO,\n"
# 21 "data/maps/RustboroCity_House2/scripts.pory"
	.string "sabe un montón sobre los POKéMON.\p"
# 22 "data/maps/RustboroCity_House2/scripts.pory"
	.string "¡Y es muy fuerte!$"
