# 1 "data/maps/PacifidlogTown_House1/scripts.pory"

# 2 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_MapScripts::
# 3 "data/maps/PacifidlogTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/PacifidlogTown_House1/scripts.pory"

# 5 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Man::
# 6 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
# 7 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 8 "data/maps/PacifidlogTown_House1/scripts.pory"

# 9 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_EventScript_Woman::
# 10 "data/maps/PacifidlogTown_House1/scripts.pory"
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
# 11 "data/maps/PacifidlogTown_House1/scripts.pory"
	end
# 12 "data/maps/PacifidlogTown_House1/scripts.pory"

# 13 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_RegiStory:
# 14 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "En la región de HOENN, hay tres\n"
# 15 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "POKéMON que representan el poder\l"
# 16 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "de la roca, el hielo y el acero.\p"
# 17 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Cada uno de ellos se esconde\n"
# 18 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "en lo más profundo de una cueva.\p"
# 19 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Ésa es la historia que me contaban\n"
# 20 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "cuando era pequeñito.$"
# 21 "data/maps/PacifidlogTown_House1/scripts.pory"

# 22 "data/maps/PacifidlogTown_House1/scripts.pory"
PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
# 23 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "“Seis puntos abren tres puertas.”\p"
# 24 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "Es lo que repetía mi abuelo, pero no\n"
# 25 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "tengo ni idea de qué quería decir…$"
