MauvilleCity_Inside_House4_MapScripts::
	.byte 0


MauvilleCity_Inside_House4_Scripts_OldMan::
# 4 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	faceplayer
# 5 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	lockall
# 6 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	msgbox MauvilleCity_Inside_House4_Text_OldMan
# 7 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	closemessage
# 8 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	releaseall
	return


MauvilleCity_Inside_House4_Scripts_Plushie::
# 12 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	msgbox MauvilleCity_Inside_House4_Text_Plushie
# 13 "data/maps/MauvilleCity_Inside_House4/scripts.pory"
	closemessage
	return

