# 1 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 2 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_MapScripts::
# 3 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.byte 0
# 4 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 5 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt14::
# 6 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_Text_Grunt14Intro, MagmaHideout_2F_1R_Text_Grunt14Defeat
# 7 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt14PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 9 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 10 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt3::
# 11 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_Text_Grunt3Intro, MagmaHideout_2F_1R_Text_Grunt3Defeat
# 12 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt3PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 14 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 15 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt4::
# 16 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_Text_Grunt4Intro, MagmaHideout_2F_1R_Text_Grunt4Defeat
# 17 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt4PostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 19 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 20 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_EventScript_Grunt5::
# 21 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_Text_Grunt5Intro, MagmaHideout_2F_1R_Text_Grunt5Defeat
# 22 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt5PostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	end
# 24 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 25 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14Intro:
# 26 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¿Y esto? Pero vamos a ver…\p"
# 27 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Los únicos que pueden estar aquí son\n"
# 28 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "los miembros del EQUIPO MAGMA!\p"
# 29 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Y tú no llevas el uniforme\n"
# 30 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "del EQUIPO MAGMA…\p"
# 31 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Has levantado mis sospechas!\n"
# 32 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Te voy a dar para el pelo!$"
# 33 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 34 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14Defeat:
# 35 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Ay, ay, ay…\n"
# 36 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Me has machacado el orgullo…$"
# 37 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 38 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt14PostBattle:
# 39 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Si siempre tienes frío, deberías\n"
# 40 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "unirte al EQUIPO MAGMA.$"
# 41 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 42 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt3Intro:
# 43 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Los pies quietos!\p"
# 44 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¿No esperarás que cierre el pico y\n"
# 45 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "deje que te pires por tu cara bonita?$"
# 46 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 47 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt3Defeat:
# 48 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Vale, vale, vale!\n"
# 49 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Me rindo!$"
# 50 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 51 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt3PostBattle:
# 52 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Quizás hubiera sido mejor hacer\n"
# 53 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "como que no te había visto…$"
# 54 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 55 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt4Intro:
# 56 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Ajá!\n"
# 57 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Tú te has colado!$"
# 58 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 59 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt4Defeat:
# 60 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Aaaaah!$"
# 61 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 62 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt4PostBattle:
# 63 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Perder, ya he perdido.\p"
# 64 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¿Qué sentido tiene seguir\n"
# 65 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "dando vueltas?$"
# 66 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 67 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5Intro:
# 68 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Vaya, vaya, vaya!\n"
# 69 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "¡Si se nos ha infiltrado alguien!$"
# 70 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 71 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5Defeat:
# 72 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Me has dejado sin palabras…$"
# 73 "data/maps/MagmaHideout_2F_1R/scripts.pory"

# 74 "data/maps/MagmaHideout_2F_1R/scripts.pory"
MagmaHideout_2F_1R_Text_Grunt5PostBattle:
# 75 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "La verdad es que no se me da bien\n"
# 76 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "luchar…$"
