gText_Birch_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "Hi! My name's Birch.\p"
	.string "But everyone knows me as Professor.\p"
	.string "$"

gText_Birch_Pokemon::
# 12 "data/text/birch_speech.pory"
	.string "\p$"

gText_Birch_Pronouns::
# 16 "data/text/birch_speech.pory"
	.string "What pronouns would\n"
	.string "you want to go by?$"

gText_Birch_MainSpeech::
# 27 "data/text/birch_speech.pory"
	.string "I love them with all my heart…\p"
	.string "That's why I've dedicated my life to\n"
	.string "study their every aspect…\p"
	.string "But enough of me!\p"
	.string "$"

gText_Birch_AndYouAre::
# 38 "data/text/birch_speech.pory"
	.string "Who are you more like?\p"
	.string "$"

gText_Birch_BoyOrGirl::
# 49 "data/text/birch_speech.pory"
	.string "Brendan? Or perhaps May?$"

gText_Birch_WhatsYourName::
# 60 "data/text/birch_speech.pory"
	.string "Great!\n"
	.string "What do you want to go by?$"

gText_Birch_SoItsPlayer::
# 71 "data/text/birch_speech.pory"
	.string "{PLAYER}?$"

gText_Birch_YourePlayer::
# 83 "data/text/birch_speech.pory"
	.string "Perfect! You're {PLAYER}, who moved\n"
	.string "here from Johto!\p"
	.string "$"

gText_Birch_AreYouReady::
# 94 "data/text/birch_speech.pory"
	.string "Your very own journey will start.\n"
	.string "You'll meet people, Pokémon and the\l"
	.string "most diverse stories…\p"
	.string "Go now, then! To the World of Pokémon!\p"
	.string "$"

gText_Birch_YouCantBirch::
# 107 "data/text/birch_speech.pory"
	.string "N-no…\p"
	.string "That… That's MY name…\p"
	.string "Get your own name.$"

gText_Birch_WaitYoureG::
# 118 "data/text/birch_speech.pory"
	.string "Y-{PAUSE 8}you're… {PLAYER}?\p"
	.string "That's great! I'm bi!\p"
	.string "Really though, choose an ACTUAL\n"
	.string "name…\p"
	.string "Unless you want everyone to call you\n"
	.string "that.\p"
	.string "You want your name to be {PLAYER}?$"

gText_Birch_TheSameAsDaughter::
# 132 "data/text/birch_speech.pory"
	.string "Ah, just like my daughter, then!\p"
	.string "Hope it's not too confusing…\n"
	.string "Is {PLAYER} alright?$"

gText_Birch_TheSameAsSon::
# 143 "data/text/birch_speech.pory"
	.string "Ah, just like my son, then!\p"
	.string "Hope it's not too confusing…\n"
	.string "Is {PLAYER} alright?$"

gText_Birch_NotVeryOriginal::
# 154 "data/text/birch_speech.pory"
	.string "Ah, {PLAYER}, then!\p"
	.string "Not very original, are we?\p"
	.string "So, is {PLAYER} alright?$"
