Unknown::
# 1 "data/text/name_boxes.pory"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}???$"

Rydel::
# 5 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Rydel$"

Birch::
# 9 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Profesor Birch$"

Collector::
# 16 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Coleccionista$"

BirchEng::
# 22 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Professor Birch$"

EmpleadoDevon::
# 26 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Empleado Devon$"

Norman::
# 32 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Papá$"

Mama::
# 39 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Mamá$"

Marta::
# 46 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Marta$"

Rival::
# 49 "data/text/name_boxes.pory"
	.string "{COLOR_RIVAL}{RIVAL}$"

Roxanne::
# 52 "data/text/name_boxes.pory"
	.string "{COLOR RED}Roxanne$"

Brawly::
# 55 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Brawly$"

Wattson::
# 58 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Wattson$"

Flannery::
# 61 "data/text/name_boxes.pory"
	.string "{COLOR RED}Flannery$"

Winona::
# 64 "data/text/name_boxes.pory"
	.string "{COLOR RED}Winona$"

Tate::
# 67 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Tate$"

Liza::
# 70 "data/text/name_boxes.pory"
	.string "{COLOR RED}Liza$"

Juan::
# 73 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Juan$"

Player::
# 76 "data/text/name_boxes.pory"
	.string "{COLOR_PLAYER}{PLAYER}$"

Archie::
# 79 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Archie$"

Aqua::
# 82 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Recluta Aqua$"

Magma::
# 88 "data/text/name_boxes.pory"
	.string "{COLOR RED}Recluta Magma$"

Maxie::
# 94 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Maxie$"

Shelly::
# 97 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Shelly$"

Matt::
# 100 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Matt$"

Courtney::
# 103 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Courtney$"

Tabitha::
# 106 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Tabitha$"

Steven::
# 109 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_BLUE}{SHADOW BLUE}Steven$"

Wallace::
# 112 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wallace$"

Wally::
# 115 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_GREEN}{SHADOW GREEN}Wally$"

Phoebe::
# 118 "data/text/name_boxes.pory"
	.string "{COLOR RED}{SHADOW LIGHT_RED}Phoebe$"

Glacia::
# 121 "data/text/name_boxes.pory"
	.string "{COLOR RED}{SHADOW LIGHT_RED}Glacia$"

Drake::
# 124 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Drake$"

Sidney::
# 127 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Sidney$"

CampeonaLeaf::
# 130 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Campeona Leaf$"

Leaf::
# 136 "data/text/name_boxes.pory"
	.string "{COLOR LIGHT_RED}{SHADOW RED}Leaf$"

PapaWally::
# 139 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Papá de Wally$"

TioWally::
# 145 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Tío de Wally$"

MamaWally::
# 151 "data/text/name_boxes.pory"
	.string "{COLOR RED}Mamá de Wally$"

TiaWally::
# 157 "data/text/name_boxes.pory"
	.string "{COLOR RED}Tía de Wally$"

Cientifico::
# 163 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Científico$"

Alex::
# 169 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Alex$"

Esmeralda::
# 172 "data/text/name_boxes.pory"
	.string "{COLOR RED}Esmeralda$"

NoDeberiasVerlo::
# 175 "data/text/name_boxes.pory"
	.string "No tendrías que poder ver esto.\n"
	.string "Si ves este mensaje, contacta al\l"
	.string "desarrollador y dile cómo y porqué\l"
	.string "este evento se mostró.$"

Riley::
# 181 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Riley$"

Wanda::
# 184 "data/text/name_boxes.pory"
	.string "{COLOR RED}Wanda$"

Camilo::
# 187 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Camilo$"

Stern::
# 190 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Stern$"

Briney::
# 193 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Briney$"

Scott::
# 196 "data/text/name_boxes.pory"
	.string "{COLOR GREEN}Scott$"

Carlos::
# 199 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Carlos$"

RecoveredItems::
# 202 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus objetos!$"

RecoveredPokemon::
# 208 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus Pokémon!$"

RecoveredPokemonAndItems::
# 214 "data/text/name_boxes.pory"
	.string "¡Has recuperado tus Pokémon y objetos!$"

Chico::
# 220 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Bully$"

Gabby::
# 223 "data/text/name_boxes.pory"
	.string "{COLOR RED}Gabby$"

Ty::
# 226 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Ty$"

Delta::
# 229 "data/text/name_boxes.pory"
	.string "{COLOR GREEN}Delta$"

Entrevistador::
# 232 "data/text/name_boxes.pory"
	.string "{COLOR BLUE}Entrevistador$"
