LavaridgeTown_House_2_Text_FlanneryGrandma::
# 3 "data/text/npc_dialogue.pory"
	.string "Flannery se ha estado\n"
	.string "sobre-esforzando para ser una buena\l"
	.string "Líder de Gimnasio.\p"
	.string "Sin la guianza de mi esposo… Se está\n"
	.string "pasando…\p"
	.string "Me preocupa que vaya a conocer a\n"
	.string "Arceus si continúa ignorando las\l"
	.string "plegarias de su cuerpo…$"

LavaridgeTown_House_2_Text_FlanneryGrandmaRelieved::
# 18 "data/text/npc_dialogue.pory"
	.string "Últimamente, Flannery está más\n"
	.string "tranquila. ¡Hasta parece otra!\p"
	.string "O, más bien… Es la versión suya que\n"
	.string "siempre quiso ser…\p"
	.string "Fuerte, apasionada como las llamas, y\n"
	.string "alguien que se cuida bien.\p"
	.string "¡Seguro será una buena mentora para\n"
	.string "algún jóven Entrenador un día!$"

LavaridgeTown_House_2_Text_FlanneryGrandmaProud::
# 35 "data/text/npc_dialogue.pory"
	.string "¡No me lo vas a creer!\n"
	.string "¡Flannery vino temprano a decirme que\l"
	.string "ayudó a un jóven Entrenador hoy!\p"
	.string "Le dije que su abuelo estaría tan, si no\n"
	.string "es que más, orgulloso de lo que yo\l"
	.string "estoy de ella.\p"
	.string "¡Parecía que sus ojos estaban usando\n"
	.string "Cascada, jajajaja!\l"
	.string "¡Deberías haberla visto!$"

LavaridgeTown_House_2_Text_FlanneryBrother::
# 50 "data/text/npc_dialogue.pory"
	.string "Desde pequeño siempre me gustó la\n"
	.string "actuación.\p"
	.string "Flannery y yo jugábamos a los\n"
	.string "actores…\p"
	.string "¡Y ella SIEMPRE ignoraba el guión para\n"
	.string "no perder las batallas!$"

LavaridgeTown_House_2_Text_FlanneryBrotherPostWally::
# 65 "data/text/npc_dialogue.pory"
	.string "Hoy temprano, Flannery vino a\n"
	.string "plantearme un guión para una\l"
	.string "película…\p"
	.string "¡Cosa rara! ¡Siempre tuve que hacerlas\n"
	.string "yo!\p"
	.string "Claramente, no era muy bueno. Pero la\n"
	.string "premisa me gustó:\p"
	.string "¡Una Entrenadora que se convierte en\n"
	.string "Campeona a pesar de su enfermedad!$"

LavaridgeTown_House_3_Text_Wife1::
# 82 "data/text/npc_dialogue.pory"
	.string "Pasamos muchos dolores con mi\n"
	.string "esposa…\p"
	.string "¡Pero nuestros queridos Delcatty\n"
	.string "siempre estuvieron para nosotras!$"

LavaridgeTown_House_3_Text_Wife2::
# 95 "data/text/npc_dialogue.pory"
	.string "¡Fue una gran sorpresa cuando del\n"
	.string "Huevo del Delcatty de mi mujer salió\l"
	.string "un Pokémon Shiny!\p"
	.string "Ah, son como nosotras, ¿Sabes? ¡Dos\n"
	.string "personas nacidas en Regiones\l"
	.string "distintas que lograron conocerse y\l"
	.string "enamorarse!$"

MtChimney_Text_KeepMakingMoreLand::
# 111 "data/text/npc_dialogue.pory"
	.string "¡A la Muk los Pokémon!\p"
	.string "¡TE VOY A PARTIR LA MADRE CON MIS\n"
	.string "PROPIAS MANOS!$"

MtChimney_Text_LessHabitatForWaterPokemon::
# 123 "data/text/npc_dialogue.pory"
	.string "¿Ah, sí? ¿¡Quieres pelea!?\p"
	.string "¡NO VOY A CONTENERME! ¡VAMOS A PELEAR!$"

MtChimney_Text_AquasNameSimilar::
# 136 "data/text/npc_dialogue.pory"
	.string "¡PRIMERO! ¡Éste me roba a mi esposa!\p"
	.string "¡¿Y AHORA ME ROBA LA IDEA DEL\n"
	.string "EQUIPO?!\p"
	.string "¡OOOOHH, ME TIENE PODRIDO!$"

MtChimney_Text_MagmasNameSimilar::
# 151 "data/text/npc_dialogue.pory"
	.string "¡PRIMERO! ¡Éste me roba a mi marido!\p"
	.string "¡¿Y AHORA ME ROBA LA IDEA DEL\n"
	.string "EQUIPO?!\p"
	.string "¡OOOOHH, ME TIENE PODRIDO!$"

gText_HealPokemonTraditionally::
# 183 "data/text/npc_dialogue.pory"
	.string "¡Ayúdenme a curar a los Pokémon de est{EA}\n"
	.string "Entrenador{A}!$"

DewfordTown_Text_BrineyLandedInSlateportDeliverGoods::
# 493 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Hemos arribado a CIUDAD PORTUAL!\p"
	.string "Supongo que vas a visitar al CAP.\n"
	.string "BABOR y entregar las PIEZAS DEVON,\l"
	.string "¿no es así?$"

Route109_Text_BrineySailToDewfordQuestion::
# 511 "data/text/npc_dialogue.pory"
	.string "¿No vas a entregar\n"
	.string "las PIEZAS DEVON?\p"
	.string "¿Quieres volver a AZULIZA?$"

Route109_Text_BrineyDewfordItIs::
# 527 "data/text/npc_dialogue.pory"
	.string "¡Pues rumbo a AZULIZA!\p"
	.string "¡Levad anclas!\n"
	.string "¡PEEKO, bonito, nos vamos!$"

Route109_Text_BrineyDeliverDevonGoods::
# 542 "data/text/npc_dialogue.pory"
	.string "Pues ve a entregar\n"
	.string "las PIEZAS DEVON. Yo te espero.$"

DewfordTown_Text_BrineyLandedInSlateport::
# 555 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Hemos arribado a CIUDAD PORTUAL!\p"
	.string "Cuando quieras volver a hacerte\n"
	.string "a la mar, me lo dices, ¿eh?$"

Route109_Text_BrineyWhereAreWeBound::
# 572 "data/text/npc_dialogue.pory"
	.string "¡Eh, grumete!\n"
	.string "¡Yo levo anclas cuando quieras!\p"
	.string "Venga, ¿adónde vamos?$"

Route109_Text_BrineyTellMeWhenYouNeedToSail::
# 590 "data/text/npc_dialogue.pory"
	.string "Cuando quieras volver\n"
	.string "a hacerte a la mar, llámame.$"

Route109_Text_ChillAtMyPapasSpot::
# 603 "data/text/npc_dialogue.pory"
	.string "¡Entrenadores, aquí!\n"
	.string "Ya sean ardientes cual fuego,\l"
	.string "o se le den bien cualquier juego,\l"
	.string "¡mi papá les romperá los huevos!$"

Route109_Text_LittleKidsDartAround::
# 620 "data/text/npc_dialogue.pory"
	.string "Los niños pueden perderse de vista\n"
	.string "en un segundo…\p"
	.string "Tienes que estar siempre pendiente\n"
	.string "de ellos. Es agotador.\p"
	.string "El mío está con mi POKéMON, así\n"
	.string "que debe de estar bien…$"

Route109_Text_SandCastleTakingLongTime::
# 640 "data/text/npc_dialogue.pory"
	.string "Estamos… tardando un montón… en\n"
	.string "terminar nuestro… castillo de arena…\p"
	.string "………… ………… ………… …………$"

Route109_Text_YouCanHaveThis::
# 653 "data/text/npc_dialogue.pory"
	.string "¡Toma esto para ti!$"

Route109_Text_WereGoingToMakeBigCastle::
# 664 "data/text/npc_dialogue.pory"
	.string "Usaremos… toda la arena para este…\n"
	.string "castillo de arena…\p"
	.string "Tú serás… nuestra servidumbre…$"

Route109_Text_ZigzagoonPicksUpLitter::
# 675 "data/text/npc_dialogue.pory"
	.string "El agua de esta zona está limpia.\p"
	.string "Pero, a veces, mi ZIGZAGOON recoge\n"
	.string "basura en la orilla…\p"
	.string "Cuando el agua sucia se evapora, cae en\n"
	.string "forma de lluvia y va a parar a los ríos,\l"
	.string "de los que se saca el agua potable.\p"
	.string "Si contaminamos el mar, acabamos\n"
	.string "pagando el pato nosotros.$"

Route109_Text_ZigzagoonCry::
# 699 "data/text/npc_dialogue.pory"
	.string "ZIGZAGOON: ¿Zigzaaa? :($"

Route109_Text_SeashoreHouseSign::
# 710 "data/text/npc_dialogue.pory"
	.string "CASA de la PLAYA\p"
	.string "“¡Combates al rojo vivo!\n"
	.string "¡Sólo para ENTRENADORES apasionados!”$"

Route109_Text_TrainerTipsSign::
# 725 "data/text/npc_dialogue.pory"
	.string "PISTAS para ENTRENADORES\p"
	.string "POKéMON que tienen el mismo nivel\n"
	.string "pueden tener distintas habilidades.\p"
	.string "Dicen que los POKéMON entrenados por\n"
	.string "ENTRENADORES se vuelven más fuertes\l"
	.string "que los POKéMON salvajes.$"

MauvilleCity_EvoMart_Text_AzurillGirl::
# 747 "data/text/npc_dialogue.pory"
	.string "Los Tutores del medio se especializan\n"
	.string "en categorías específicas,\l"
	.string "¡Pero los que tienen sus propios\l"
	.string "cuartos enseñan ataques\l"
	.string "personalizados para cada Pokémon!$"

MauvilleCity_EvoMart_Text_HereToBuy::
# 760 "data/text/npc_dialogue.pory"
	.string "¡Esta ciudad es increíble!\p"
	.string "¿Cuatro Tutores de Movimientos en una\n"
	.string "tienda?\p"
	.string "¡Nunca me dejo de sorprender aquí!$"

MauvilleCity_EvoMart_Text_PledgeMoveTutor::
# 771 "data/text/npc_dialogue.pory"
	.string "¡Soy el Tutor de Votos!\p"
	.string "Por dos Partes de cualquier color\n"
	.string "{COLOR LIGHT_GRAY SHADOW WHITE}aunque las mejores son las Amarillas{COLOR DARK_GRAY SHADOW LIGHT_GRAY},\l"
	.string "¡Le enseñaré a tus Pokémon un\l"
	.string "Movimiento Voto!\p"
	.string "¿Intentamos?$"

MauvilleCity_EvoMart_Text_UltimateMoveTutor::
# 782 "data/text/npc_dialogue.pory"
	.string "¡Soy la Tutora Suprema!\p"
	.string "Por cinco Partes de cualquier color\n"
	.string "menos amarillo, ¡Le enseñaré a tus\l"
	.string "Pokémon un Movimiento Supremo!\p"
	.string "¿Intentamos?$"

MauvilleCity_EvoMart_Text_EggMoveTutor::
# 793 "data/text/npc_dialogue.pory"
	.string "¡Hola, soy la reconocida Tutora de\n"
	.string "Movimientos Huevo!\p"
	.string "Por 10 Partes Verdes puedo enseñarle\n"
	.string "un Movimiento Huevo a tu Pokémon,\l"
	.string "¡Y no te preocupes, si es una\l"
	.string "evolución podré enseñarle ataques de\l"
	.string "etapas anteriores!\p"
	.string "¿Quieres probar?$"

MauvilleCity_EvoMart_Text_EggMoveTutorNotEnough::
# 810 "data/text/npc_dialogue.pory"
	.string "¡Te faltan Partes Verdes! ¡Recuerda que\n"
	.string "necesitas 10!\p"
	.string "Pero…$"

MauvilleCity_EvoMart_Text_SelectMoveTutor::
# 823 "data/text/npc_dialogue.pory"
	.string "¿Qué movimiento debería enseñarle a\n"
	.string "tus Pokémon?$"

MauvilleCity_EvoMart_Text_DeclineTutor::
# 834 "data/text/npc_dialogue.pory"
	.string "¡No pasa nada!\n"
	.string "¡Vuelve pronto!$"

MauvilleCity_EvoMart_Text_TutorNotEnough::
# 845 "data/text/npc_dialogue.pory"
	.string "Ah, ¿Te faltan Partes?\p"
	.string "¡Vuelve pronto!$"

MauvilleCity_EvoMart_Text_TutorSelectMon::
# 856 "data/text/npc_dialogue.pory"
	.string "¡Perfecto!\n"
	.string "¿A qué Pokémon debería enseñarle un\l"
	.string "movimiento?$"

MauvilleCity_EvoMart_Text_TutorIncompatible::
# 867 "data/text/npc_dialogue.pory"
	.string "Ah, disculpa, pero eso va más allá de mis\n"
	.string "capacidades…$"

MauvilleCity_EvoMart_Text_TutorDone::
# 878 "data/text/npc_dialogue.pory"
	.string "¡Todo listo! ¡{STR_VAR_1}\n"
	.string "aprendió {STR_VAR_2}!$"

MauvilleCity_EvoMart_Text_TutorBye::
# 889 "data/text/npc_dialogue.pory"
	.string "¡Gracias por todo!$"

MauvilleCity_EvoMart_Text_SignatureMoveTutor::
# 901 "data/text/npc_dialogue.pory"
	.string "¡Soy el Tutor Característico!\p"
	.string "Por cinco Partes de cualquier color, ¡Le\n"
	.string "enseñaré a tus Pokémon su Movimiento\l"
	.string "Característico!\p"
	.string "¿Intentamos?$"

MauvilleCity_Inside_Text_Guitarist::
# 914 "data/text/npc_dialogue.pory"
	.string "¡Bro! ¡Tanta gente pasa al azar, bro!\n"
	.string "¡Tanta gente a la que cantarles mi\l"
	.string "nueva canción, bro!$"

MauvilleCity_Inside_Text_AromaLady::
# 927 "data/text/npc_dialogue.pory"
	.string "Odio esta ciudad, pero es la única con\n"
	.string "electrididad gratis…\p"
	.string "Todo es tan anti-natural aquí, ¿Y me\n"
	.string "tiene que gustar sólo por una factura\l"
	.string "menos?$"

MauvilleCity_Inside_Text_BlackBelt::
# 940 "data/text/npc_dialogue.pory"
	.string "¿Sabías que todos los días hay\n"
	.string "personas distintas en el Café\l"
	.string "Combate?\p"
	.string "¡Y suben de nivel basados en tus\n"
	.string "Medallas actuales! ¡Siempre es un\l"
	.string "desafío!$"

MauvilleCity_Inside_Text_Sawk::
# 953 "data/text/npc_dialogue.pory"
	.string "Sawk.$"

MauvilleCity_Inside_Text_OldWoman::
# 964 "data/text/npc_dialogue.pory"
	.string "Parece como si hubiese sido ayer cuando\n"
	.string "escondí un cuerpo en la tierra debajo\l"
	.string "de este mismo azulejo…\l"
	.string "¡Cómo vuela el tiempo!$"

MauvilleCity_Inside_Text_OldMan1::
# 977 "data/text/npc_dialogue.pory"
	.string "Hoy día,{PAUSE 8} el {COLOR BLUE}Área Residencial{COLOR DARK_GRAY} está en el\n"
	.string "segundo piso,\l"
	.string "y el {COLOR RED}Área Comercial{COLOR DARK_GRAY}, en el primero,\l"
	.string "pero…\p"
	.string "¡No había NINGÚN piso cuando era más\n"
	.string "joven! Hasta hace algunos años, era\l"
	.string "una ciudad común y corriente.$"

MauvilleCity_Inside_Text_OldMan2::
# 992 "data/text/npc_dialogue.pory"
	.string "Fue difícil adaptarse, no mentiré, pero\n"
	.string "al menos nuestras casas fueron\l"
	.string "replicadas.\p"
	.string "Nadie tenía dos pisos, ni papel de pared\n"
	.string "propio, así que el proceso fue simple…\p"
	.string "Arceus, ¿En serio teníamos tan pocas\n"
	.string "cosas?$"

MauvilleCity_Inside_Text_OldMan3::
# 1007 "data/text/npc_dialogue.pory"
	.string "Gracias por escuchar a un viejo\n"
	.string "divagar… ¡Ten, la MT Canon, un\l"
	.string "movimiento que se potencia mientras\l"
	.string "más se use!\p"
	.string "¡También obliga a aliados que lo\n"
	.string "conozcan a repetirlo! Podrías\l"
	.string "terminar usándolo cuatro veces en un\l"
	.string "turno de Batalla Doble.$"

MauvilleCity_Inside_Text_OldManExplainTMRound::
# 1020 "data/text/npc_dialogue.pory"
	.string "Canon es un movimiento que se potencia\n"
	.string "mientras más se use.\p"
	.string "¡También obliga a aliados que lo\n"
	.string "conozcan a repetirlo! Podrías\l"
	.string "terminar usándolo cuatro veces en un\l"
	.string "turno de Batalla Doble.$"

MauvilleCity_Inside_Text_Tourist4A::
# 1033 "data/text/npc_dialogue.pory"
	.string "¡Podría perderme en esta ciudad!\n"
	.string "……Bueno, no. Estoy exagerando.$"

MauvilleCity_Inside_Text_Tourist4B::
# 1044 "data/text/npc_dialogue.pory"
	.string "Lo que le falta a esta ciudad… No se lo\n"
	.string "puedo decir a un{A} niñ{OA}…$"

MauvilleCity_Inside_Text_Tourist4C::
# 1055 "data/text/npc_dialogue.pory"
	.string "Vine aquí desde Kalos para ver el\n"
	.string "avance de la infraestructura de\l"
	.string "Hoenn.\p"
	.string "7.5/10. Demasiado naranja.$"

MauvilleCity_Inside_Text_Tourist4D::
# 1068 "data/text/npc_dialogue.pory"
	.string "Vine a comparle algo a mi esposa por\n"
	.string "nuestro aniversario.\p"
	.string "Y a comprarle algo para que me regale a\n"
	.string "mí, ya que seguro lo volvió a olvidar.$"

MauvilleCity_Inside_House3_Text_Mom1::
# 1081 "data/text/npc_dialogue.pory"
	.string "Mi mujer y yo llevamos años en la Ciudad,\n"
	.string "¡qué bueno que pudimos mantener\l"
	.string "nuestra casa intacta!\p"
	.string "¡Hasta nos dieron nuevos muebles!$"

MauvilleCity_Inside_House3_Text_Mom1_Darling::
# 1094 "data/text/npc_dialogue.pory"
	.string "Ay, querida, no metas a la gente que nos\n"
	.string "visita en esto…$"

MauvilleCity_Inside_House3_Text_Mom2::
# 1105 "data/text/npc_dialogue.pory"
	.string "¿Tengo razón o no?$"

MauvilleCity_Inside_House3_Text_Mom2_Yes::
# 1116 "data/text/npc_dialogue.pory"
	.string "¿Eh? ¡No me des la razón como a los\n"
	.string "locos!$"

MauvilleCity_Inside_House3_Text_Mom2_No::
# 1127 "data/text/npc_dialogue.pory"
	.string "Ni siquiera terminé la pregunta…$"

MauvilleCity_Inside_House3_Text_Girl::
# 1138 "data/text/npc_dialogue.pory"
	.string "Ay, ete mi hemanito…\p"
	.string "Siempe le agadan obsesiones y no pada\n"
	.string "de hablad…\p"
	.string "Al menos tiene decompensas… Hasta\n"
	.string "mejor que chó habla…$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy::
# 1149 "data/text/npc_dialogue.pory"
	.string "¡Ah, hola distinguid{OA} señor{A}!\p"
	.string "Tengo unos temas fantásticos de los\n"
	.string "que charlar…\p"
	.string "Aunque no soy maleducado y te dejaré\n"
	.string "irte si no quieres seguir hablando…\p"
	.string "¡Más si te quedas, te recompensaré!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_StillMore::
# 1162 "data/text/npc_dialogue.pory"
	.string "¡Aún tengo más de qué hablar!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_OneMore::
# 1173 "data/text/npc_dialogue.pory"
	.string "¡Sólo tengo un tema más para hablar!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_RewardTalkAgain::
# 1184 "data/text/npc_dialogue.pory"
	.string "¡Perfecto!\n"
	.string "¡Háblame de nuevo y te daré tu\l"
	.string "recompensa!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_GiftGiver::
# 1195 "data/text/npc_dialogue.pory"
	.string "Permíteme hablarte sobre la Habilidad\n"
	.string "Pokémon {COLOR RED}Regalador{COLOR DARK_GRAY}.\p"
	.string "Esta es la Habilidad Característica de\n"
	.string "{COLOR RED}Delibird{COLOR DARK_GRAY}, y permite al usuario usar\l"
	.string "Movimientos que dependan del Objeto\l"
	.string "Equipado,\l"
	.string "incluso si no se posee uno. Por\l"
	.string "ejemplo, ¡Don Natural usará su\l"
	.string "potencia máxima y cambiará su Tipo\l"
	.string "dependiendo de qué será más efectivo\l"
	.string "contra el rival!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_FutureVision::
# 1210 "data/text/npc_dialogue.pory"
	.string "Ahora, déjame contarte sobre la\n"
	.string "Habilidad Pokémon {COLOR RED}Visión Futura{COLOR DARK_GRAY}.\p"
	.string "Una vez más, se trata de una Habilidad\n"
	.string "Característica, de la familia\l"
	.string "evolutiva de {COLOR RED}Gothita{COLOR DARK_GRAY}.\p"
	.string "Visión Futura permite al usuario\n"
	.string "predecir la posición exacta del rival\l"
	.string "en todo futuro posible, ¡pudiendo así\l"
	.string "tener precisión perfecta con\l"
	.string "Movimientos Tipo Psíquico!\p"
	.string "Como te imaginarás, combina\n"
	.string "perfectamente con Movimientos como\l"
	.string "Hipnosis…$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_ColonysAid::
# 1227 "data/text/npc_dialogue.pory"
	.string "Por último, centrémonos en otra\n"
	.string "Habilidad Pokémon Característica,\l"
	.string "{COLOR RED}Socorro Colonial{COLOR DARK_GRAY}.\p"
	.string "Es la Habilidad de {COLOR RED}Durant{COLOR DARK_GRAY}.\p"
	.string "Al perder un 25% de sus PS, Durant\n"
	.string "activa Socorro Colonial, y otro Durant\l"
	.string "hace de Sustituto, uno con 1/4 de\l"
	.string "salud, por supuesto,\l"
	.string "¡Y esto se activa cada vez que Durant\l"
	.string "pierde 25% de PS! ¡Qué gran mecanismo\l"
	.string "de defensa!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_Congrats::
# 1244 "data/text/npc_dialogue.pory"
	.string "¡Muchas gracias por escucharme,\n"
	.string "estimad{OA} señor{A}!\p"
	.string "¡Como recompensa, podrá elegir uno de\n"
	.string "los Pokémon de los que hablamos!$"

MauvilleCity_Inside_House3_Text_HyperfixatedBoy_Thanks::
# 1256 "data/text/npc_dialogue.pory"
	.string "¡Muchas gracias por escucharme,\n"
	.string "estimad{OA} señor{A}!$"

MauvilleCity_Inside_House4_Text_OldMan::
# 1268 "data/text/npc_dialogue.pory"
	.string "Conseguir nuevos Peluches Pokémon es\n"
	.string "algo complicado…\p"
	.string "¡Ojalá existiera alguna máquina de\n"
	.string "garra para conseguirlos! ¡Aunque sea\l"
	.string "uno chiquito!$"

MauvilleCity_Inside_House4_Text_Plushie::
# 1280 "data/text/npc_dialogue.pory"
	.string "Un Peluche Pokémon muy costoso… Te\n"
	.string "están entrando ganas de robarlo…$"

MauvilleCity_Inside_CandyShop_Text_Employee::
# 1292 "data/text/npc_dialogue.pory"
	.string "¡Bienvenid{OA} a la Tienda de Golosinas!\p"
	.string "¿Qué te gustaría comprar?$"

MauvilleCity_Inside_CandyShop_Text_EmployeeSweet::
# 1303 "data/text/npc_dialogue.pory"
	.string "¡Bienvenid{OA} a la Tienda de Confites!\p"
	.string "¿Qué te gustaría comprar?$"

MauvilleCity_Inside_CandyShop_Text_EmployeeBye::
# 1314 "data/text/npc_dialogue.pory"
	.string "¡Vuelve pronto!$"

MauvilleCity_Inside_CandyShop_Text_MomNearSameKids::
# 1325 "data/text/npc_dialogue.pory"
	.string "Mi hijo y sus amigos se parecen\n"
	.string "bastante, y encima les encanta\l"
	.string "vestirse igual…\p"
	.string "Una vez me llevé al hijo equivocado de\n"
	.string "una pijamada que hicieron…$"

MauvilleCity_Inside_CandyShop_Text_BlueBoy1::
# 1338 "data/text/npc_dialogue.pory"
	.string "¿Somos amigos porque somos iguales?\p"
	.string "¿O nos hicimos iguales por ser amigos?$"

MauvilleCity_Inside_CandyShop_Text_BlueBoy2::
# 1349 "data/text/npc_dialogue.pory"
	.string "Sadly I don't speak Spanish, but I DO\n"
	.string "love my friends!$"

MauvilleCity_Inside_CandyShop_Text_BlueBoy3::
# 1360 "data/text/npc_dialogue.pory"
	.string "¿Y? ¿Qué vamos a comprar? ¡Tengo\n"
	.string "hambre!$"

MauvilleCity_Inside_CandyShop_Text_BoyFridge::
# 1371 "data/text/npc_dialogue.pory"
	.string "Cuando mi yaya me quite la vista de\n"
	.string "encima, tío…\p"
	.string "¡Agarro tres bolsas de caramelos y me\n"
	.string "voy pitando!$"

MauvilleCity_Inside_CandyShop_Text_Grandma::
# 1382 "data/text/npc_dialogue.pory"
	.string "A este se le da por hacerse el Paldeano\n"
	.string "Y por robar…\p"
	.string "No me da un descanso el chaval-\p"
	.string "¡Ah! ¡Es contagioso!$"

MauvilleCity_Inside_CandyShop_Text_Girl::
# 1393 "data/text/npc_dialogue.pory"
	.string "Es el cumpleaños de mi Papá, y traje a su\n"
	.string "cónyuge a que le compre algo, porque\l"
	.string "sé que sin mí, no lo haría el muy vague.$"

MauvilleCity_Inside_CandyShop_Text_NonBinaryParent::
# 1404 "data/text/npc_dialogue.pory"
	.string "Es el cumpleaños de mi marido, y eso de\n"
	.string "comprarle dulces no me convence.\p"
	.string "Pero mi hija me toma de vague si no\n"
	.string "vengo…\p"
	.string "Y eso que estoy esperando el regalo que\n"
	.string "le compré por Mercado Butterfree, y\l"
	.string "otro más por Temuk…$"

MauvilleCity_ToyStore_Text_OldMan::
# 1419 "data/text/npc_dialogue.pory"
	.string "¡Hola, esta es la Juguetería Mauville!\p"
	.string "¿Qué te gustaría comprar?$"

MauvilleCity_ToyStore_Text_Artist::
# 1430 "data/text/npc_dialogue.pory"
	.string "¿Te gustan los peluches que vendemos\n"
	.string "aquí?\p"
	.string "¡Soy el artista que los fabrica!\n"
	.string "Quizá si esperas más tiempo, quizá\l"
	.string "tengamos más…$"

MauvilleCity_CommunalGarden_Text_Ranger1::
# 1441 "data/text/npc_dialogue.pory"
	.string "¡Bienvenid{OA} al Jardín Comunal Mauville!\n"
	.string "¡Donde Pokémon y Humanos conviven en\l"
	.string "harmonía!$"

MauvilleCity_CommunalGarden_Text_Ranger2::
# 1452 "data/text/npc_dialogue.pory"
	.string "… Bienvenid{OA} al Jardín Comunal Mauville…\n"
	.string "Zzz… Zzz…$"

MauvilleCity_CommunalGarden_Text_Ranger1No::
# 1463 "data/text/npc_dialogue.pory"
	.string "¿¡Otra vez!? ¿¡Por qué tuvieron que\n"
	.string "emparejarme con él!?$"

MauvilleCity_CommunalGarden_Text_OldWoman::
# 1474 "data/text/npc_dialogue.pory"
	.string "Este lugar… ¡Qué idea tan estúpida!\n"
	.string "A los Pokémon no les gusta estar\l"
	.string "encerrados así,\l"
	.string "y más aún en un lugar con tantas\l"
	.string "luces artificiales y electricidad…\p"
	.string "Sólo a los Voltorb les gusta vivir así…$"

MauvilleCity_CommunalGarden_Text_Boy::
# 1489 "data/text/npc_dialogue.pory"
	.string "Escuché a mi Papá decirle a su novio que\n"
	.string "Devon cree que este es el futuro de\l"
	.string "Hoenn…\p"
	.string "¡Pero hasta yo sé que a los Pokémon no\n"
	.string "les gusta vivir aquí!\p"
	.string "El otro día, salvé a un Lillipup que\n"
	.string "intentó tirarse al piso inferior…\l"
	.string "Desde entonces, no dejo de vigilarla,\l"
	.string "por si acaso…$"

MauvilleCity_CommunalGarden_Text_Man::
# 1504 "data/text/npc_dialogue.pory"
	.string "Entiendo que haya sido el sueño de\n"
	.string "nuestro Líder de Gimnasio, Wattson,\l"
	.string "crear una ciudad donde Pokémon y\l"
	.string "Humanos convivan.\p"
	.string "¿Pero qué no aprendió del gravísimo\n"
	.string "error que fue Nova Mauville?\p"
	.string "Todos los Pokémon que perdieron sus\n"
	.string "vidas ese día, ¿No le importan?$"

MauvilleCity_CommunalGarden_Text_Woman::
# 1518 "data/text/npc_dialogue.pory"
	.string "Muchos culpan y ya no ven bien a\n"
	.string "Wattson por las decisiones que tomó\l"
	.string "sobretodo con este Jardín.\p"
	.string "¿Pero qué no ven que está haciendo lo\n"
	.string "posible, dentro de los parámetros\l"
	.string "dados por Devon?\p"
	.string "¡Esa corporación tiene casi todo el\n"
	.string "poder!\l"
	.string "¡No dudo que Wattson se las arreglará\l"
	.string "para mejorar todo!$"

MauvilleCity_CommunalGarden_Text_Pokemon::
# 1533 "data/text/npc_dialogue.pory"
	.string "Ni siquiera te puede mirar… Este\n"
	.string "Pokémon está muy deprimido.$"

MauvilleCity_CommunalGarden_Text_BlackBeltWannaSee::
# 1545 "data/text/npc_dialogue.pory"
	.string "Si quieres, te puedo levantar para que\n"
	.string "veas mejor el piso debajo. ¡No te\l"
	.string "preocupes, soy fuerte y no te dejaré\l"
	.string "caer!$"

MauvilleCity_CommunalGarden_Text_BlackBeltYouDone::
# 1556 "data/text/npc_dialogue.pory"
	.string "¿Ya te quieres bajar?$"

MauvilleCity_CommunalGarden_Text_BlackBeltYouSure::
# 1567 "data/text/npc_dialogue.pory"
	.string "¿Y-{PAUSE 8}y ahora? ¿Te quieres bajar o no?$"

MauvilleCity_CommunalGarden_Text_BlackBeltFun::
# 1578 "data/text/npc_dialogue.pory"
	.string "¡Espero te hayas divertido!$"

Route101_Text_RaltsIsEagerForBattle::
# 1589 "data/text/npc_dialogue.pory"
	.string "Parece que este Ralts está rebosando\n"
	.string "con ganas de batallar… ¿Te\l"
	.string "involucrarás?$"

Route101_Text_RaltsIsMad::
# 1600 "data/text/npc_dialogue.pory"
	.string "Parece que este Ralts se enojó\n"
	.string "contigo…$"

Route101_Text_RaltsWasMew::
# 1611 "data/text/npc_dialogue.pory"
	.string "Parece que este Ralts… Era el Pokémon\n"
	.string "Nuevaespecie…\p"
	.string "{COLOR RED SHADOW LIGHT_RED}Mew{COLOR DARK_GRAY SHADOW LIGHT_GRAY}…$"
