AbandonedShip_Rooms2_1F_Text_DanIntro::
# 3 "data/text/npc_dialogue.pory"
	.string "DAN: While searching for treasures,\n"
	.string "we discovered a TRAINER!$"

AbandonedShip_CaptainsOffice_Text_NoSuccessFindingScanner::
# 16 "data/text/npc_dialogue.pory"
	.string "I'm investigating this ship on behalf\n"
	.string "of CAPT. STERN.\p"
	.string "He also asked me to find a SCANNER,\n"
	.string "but I haven't had any success…$"

AbandonedShip_CaptainsOffice_Text_OhCanYouDeliverScanner::
# 33 "data/text/npc_dialogue.pory"
	.string "Oh! That's a SCANNER!\p"
	.string "Listen, can I get you to deliver that\n"
	.string "to CAPT. STERN?\p"
	.string "I want to investigate this ship a\n"
	.string "little more.$"

AbandonedShip_CaptainsOffice_Text_ThisIsSSCactus::
# 52 "data/text/npc_dialogue.pory"
	.string "This ship is called S.S. CACTUS.\n"
	.string "It seems to be from an earlier era.$"

AbandonedShip_Corridors_1F_Text_CharlieIntro::
# 65 "data/text/npc_dialogue.pory"
	.string "What's so funny about having my inner\n"
	.string "tube aboard the ship?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat::
# 78 "data/text/npc_dialogue.pory"
	.string "Whoa, you overwhelmed me!$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle::
# 89 "data/text/npc_dialogue.pory"
	.string "It's not easy throwing POKé BALLS\n"
	.string "while hanging on to an inner tube!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere::
# 102 "data/text/npc_dialogue.pory"
	.string "Isn't it fun here?\n"
	.string "I get excited just being here!$"

AbandonedShip_Corridors_B1F_Text_DuncanIntro::
# 115 "data/text/npc_dialogue.pory"
	.string "When we go out to sea, we SAILORS\n"
	.string "always bring our POKéMON.\l"
	.string "How about a quick battle?$"

AbandonedShip_Corridors_B1F_Text_DuncanDefeat::
# 130 "data/text/npc_dialogue.pory"
	.string "Whoops, I'm sunk!$"

AbandonedShip_Corridors_B1F_Text_DuncanPostBattle::
# 141 "data/text/npc_dialogue.pory"
	.string "The ship's bottom has sunk into the\n"
	.string "depths.\p"
	.string "If a POKéMON knew how to go underwater,\n"
	.string "we might make some progress…$"

AbandonedShip_Corridors_B1F_Text_YayItsAShip::
# 157 "data/text/npc_dialogue.pory"
	.string "The depths of the ocean and Devon's\n"
	.string "greed have taken it all from me.\p"
	.string "My family, my hopes, and even my own\n"
	.string "childhood.\p"
	.string "108 years may pass, and still my soul\n"
	.string "will continue here to stand.$"

AbandonedShip_Corridors_B1F_Text_DoorIsLocked::
# 170 "data/text/npc_dialogue.pory"
	.string "The door is locked.\p"
	.string "“STORAGE” is painted on the door.$"

AbandonedShip_Corridors_B1F_Text_InsertedStorageKey::
# 183 "data/text/npc_dialogue.pory"
	.string "{PLAYER} inserted and turned the\n"
	.string "STORAGE KEY.\p"
	.string "The inserted KEY stuck fast,\n"
	.string "but the door opened.$"

AbandonedShip_Text_TheDoorIsOpen::
# 200 "data/text/npc_dialogue.pory"
	.string "The door is open.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm1DoorIsLocked::
# 212 "data/text/npc_dialogue.pory"
	.string "The door is locked.\p"
	.string "“RM. 1” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm2DoorIsLocked::
# 225 "data/text/npc_dialogue.pory"
	.string "The door is locked.\p"
	.string "“RM. 2” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm4DoorIsLocked::
# 238 "data/text/npc_dialogue.pory"
	.string "The door is locked.\p"
	.string "“RM. 4” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm6DoorIsLocked::
# 251 "data/text/npc_dialogue.pory"
	.string "The door is locked.\p"
	.string "“RM. 6” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_InsertedKey::
# 264 "data/text/npc_dialogue.pory"
	.string "{PLAYER} inserted and turned the\n"
	.string "KEY.\p"
	.string "The inserted KEY stuck fast,\n"
	.string "but the door opened.$"

AbandonedShip_HiddenFloorRooms_Text_BrightShinyTrash::
# 283 "data/text/npc_dialogue.pory"
	.string "It's bright and shiny!\n"
	.string "But it's just trash… Kinda like\l"
	.string "Pokémon Diamond and Pearl.$"

DewfordTown_Text_BrineyLandedInSlateportDeliverGoods::
# 300 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: Ahoy!\n"
	.string "We've made land in SLATEPORT!\p"
	.string "I suppose you're going to visit CAPT.\n"
	.string "STERN and deliver the DEVON GOODS?$"

Route109_Text_BrineySailToDewfordQuestion::
# 318 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: I thought you're supposed\n"
	.string "to deliver the DEVON GOODS.\p"
	.string "Would you like to sail back to\n"
	.string "DEWFORD, then?$"

Route109_Text_BrineyDewfordItIs::
# 334 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: DEWFORD it is, then!\p"
	.string "Anchors aweigh!\n"
	.string "PEEKO, we're setting sail, my darling!$"

Route109_Text_BrineyDeliverDevonGoods::
# 349 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: Then you go on and deliver\n"
	.string "the DEVON GOODS. I'll be waiting.$"

DewfordTown_Text_BrineyLandedInSlateport::
# 362 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: Ahoy! We've made land in\n"
	.string "SLATEPORT!\p"
	.string "You just go on and tell me whenever\n"
	.string "you want to set sail again!$"

Route109_Text_BrineyWhereAreWeBound::
# 379 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: Ahoy!\n"
	.string "For you, I'll go out to sea anytime!\p"
	.string "Now, my friend, where are we bound?$"

Route109_Text_BrineyTellMeWhenYouNeedToSail::
# 397 "data/text/npc_dialogue.pory"
	.string "MR. BRINEY: You just tell me whenever\n"
	.string "you need to set sail again!$"

Route109_Text_ChillAtMyPapasSpot::
# 410 "data/text/npc_dialogue.pory"
	.string "Yo, TRAINERS!\n"
	.string "Whether you're hot to trot,\l"
	.string "or cool cat not,\l"
	.string "chill at my papa's spot!$"

Route109_Text_LittleKidsDartAround::
# 427 "data/text/npc_dialogue.pory"
	.string "Little kids can dart around so\n"
	.string "quickly…\p"
	.string "You don't dare take your eyes off them\n"
	.string "for an instant. It's very taxing.\p"
	.string "Mine are with my POKéMON, so they\n"
	.string "should be okay, but…$"

Route109_Text_SandCastleTakingLongTime::
# 447 "data/text/npc_dialogue.pory"
	.string "Our… sand castle's… taking a long time…\n"
	.string "to make…\p"
	.string "………… ………… ………… …………$"

Route109_Text_YouCanHaveThis::
# 460 "data/text/npc_dialogue.pory"
	.string "You can have this!$"

Route109_Text_WereGoingToMakeBigCastle::
# 471 "data/text/npc_dialogue.pory"
	.string "We'll… use up all the sand for this… sand\n"
	.string "castle of ours…\p"
	.string "And you will be… our servant…$"

Route109_Text_ZigzagoonPicksUpLitter::
# 482 "data/text/npc_dialogue.pory"
	.string "The water around these parts is\n"
	.string "clean.\p"
	.string "But, I get my ZIGZAGOON to pick up\n"
	.string "litter from the shoreline at times.\p"
	.string "Dirty water becomes rain and joins our\n"
	.string "rivers, which we drink from…\p"
	.string "If we pollute the sea, it all comes\n"
	.string "back to haunt us eventually.$"

Route109_Text_ZigzagoonCry::
# 506 "data/text/npc_dialogue.pory"
	.string "ZIGZAGOON: Guguu? :($"

Route109_Text_SeashoreHouseSign::
# 517 "data/text/npc_dialogue.pory"
	.string "SEASHORE HOUSE\p"
	.string "“May hot battles rage on hot sands!\n"
	.string "The place for hot TRAINERS!”$"

Route109_Text_TrainerTipsSign::
# 532 "data/text/npc_dialogue.pory"
	.string "TRAINER TIPS\p"
	.string "POKéMON at the same level may not\n"
	.string "always have identical stats.\p"
	.string "POKéMON raised by TRAINERS are said\n"
	.string "to grow stronger than wild POKéMON.$"

AbandonedShip_Rooms2_1F_Text_DanDefeat::
# 552 "data/text/npc_dialogue.pory"
	.string "DAN: We couldn't win even though\n"
	.string "we worked together…$"

AbandonedShip_Rooms2_1F_Text_DanPostBattle::
# 557 "data/text/npc_dialogue.pory"
	.string "DAN: We can't find any treasures…\n"
	.string "I wonder if someone got them already?$"

AbandonedShip_Rooms2_1F_Text_DanNotEnoughMons::
# 562 "data/text/npc_dialogue.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraIntro::
# 567 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh?\n"
	.string "We were searching for treasures.\l"
	.string "But we discovered a TRAINER instead!$"

AbandonedShip_Rooms2_1F_Text_KiraDefeat::
# 573 "data/text/npc_dialogue.pory"
	.string "KIRA: Ooh, so strong!$"

AbandonedShip_Rooms2_1F_Text_KiraPostBattle::
# 577 "data/text/npc_dialogue.pory"
	.string "KIRA: Where could the treasures be?\p"
	.string "I've already decided what I'm buying\n"
	.string "when we find the treasures!$"

AbandonedShip_Rooms2_1F_Text_KiraNotEnoughMons::
# 583 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_KiraRegister::
# 588 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you make me so angry!\n"
	.string "I'm going to register you for that!$"

AbandonedShip_Rooms2_1F_Text_DanRematchIntro::
# 593 "data/text/npc_dialogue.pory"
	.string "DAN: We've been searching for\n"
	.string "treasures all this time.\p"
	.string "Our POKéMON have grown stronger, too.\n"
	.string "Let us show you, okay?$"

AbandonedShip_Rooms2_1F_Text_DanRematchDefeat::
# 600 "data/text/npc_dialogue.pory"
	.string "DAN: You're strong, as usual!$"

AbandonedShip_Rooms2_1F_Text_DanPostRematch::
# 604 "data/text/npc_dialogue.pory"
	.string "DAN: We can't find any treasures,\n"
	.string "we lose at POKéMON…\p"
	.string "I want to go home… But if I say that,\n"
	.string "she gets all angry with me…$"

AbandonedShip_Rooms2_1F_Text_DanRematchNotEnoughMons::
# 611 "data/text/npc_dialogue.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraRematchIntro::
# 616 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh? We meet again!\p"
	.string "Just like us, you still haven't given up\n"
	.string "searching for treasures, have you?\p"
	.string "Want to make it so the loser has\n"
	.string "to give up searching?$"

AbandonedShip_Rooms2_1F_Text_KiraRematchDefeat::
# 624 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, we lost again…$"

AbandonedShip_Rooms2_1F_Text_KiraPostRematch::
# 628 "data/text/npc_dialogue.pory"
	.string "KIRA: We're not leaving until we raise\n"
	.string "our POKéMON some more and we find\l"
	.string "the treasures here!$"

AbandonedShip_Rooms2_1F_Text_KiraRematchNotEnoughMons::
# 634 "data/text/npc_dialogue.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_JaniIntro::
# 639 "data/text/npc_dialogue.pory"
	.string "I'm not good at swimming,\n"
	.string "but I am good at battles!$"

AbandonedShip_Rooms2_1F_Text_JaniDefeat::
# 644 "data/text/npc_dialogue.pory"
	.string "Oops.\n"
	.string "That didn't go very well.$"

AbandonedShip_Rooms2_1F_Text_JaniPostBattle::
# 649 "data/text/npc_dialogue.pory"
	.string "Walking around barefoot in this ship\n"
	.string "is kind of gross.$"

AbandonedShip_Rooms2_1F_Text_GarrisonIntro::
# 654 "data/text/npc_dialogue.pory"
	.string "Strength and compassion…\n"
	.string "Those are a TRAINER's treasures!$"

AbandonedShip_Rooms2_1F_Text_GarrisonDefeat::
# 659 "data/text/npc_dialogue.pory"
	.string "Ah, there is something about you\n"
	.string "that sparkles.$"

AbandonedShip_Rooms2_1F_Text_GarrisonPostBattle::
# 664 "data/text/npc_dialogue.pory"
	.string "In a cabin somewhere on board,\n"
	.string "I saw something sparkle.$"
