# 1 "data/maps/VerdanturfTown_House/scripts.pory"

# 2 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_MapScripts::
# 3 "data/maps/VerdanturfTown_House/scripts.pory"
	.byte 0
# 4 "data/maps/VerdanturfTown_House/scripts.pory"

# 5 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman1::
# 6 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
# 7 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 8 "data/maps/VerdanturfTown_House/scripts.pory"

# 9 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman2::
# 10 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
# 11 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 12 "data/maps/VerdanturfTown_House/scripts.pory"

# 13 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
# 14 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Lejos, muy lejos, en CIUDAD COLOSALIA,\n"
# 15 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "está la LIGA POKéMON.\p"
# 16 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Los ENTRENADORES que se reúnen\n"
# 17 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "allí son espeluznantemente buenos.$"
# 18 "data/maps/VerdanturfTown_House/scripts.pory"

# 19 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_DefeatEliteFourInARow:
# 20 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Según las reglas de la LIGA POKéMON,\n"
# 21 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "tienes que luchar contra los miembros\l"
# 22 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "del ALTO MANDO uno tras otro, seguidos.\p"
# 23 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Si pierdes contra alguno de ellos, debes\n"
# 24 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "comenzar otra vez desde el primero.$"
