# 1 "data/maps/VictoryRoad_B1F/scripts.pory"

# 2 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_MapScripts::
# 3 "data/maps/VictoryRoad_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/VictoryRoad_B1F/scripts.pory"

# 5 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Samuel::
# 6 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SAMUEL, VictoryRoad_B1F_Text_SamuelIntro, VictoryRoad_B1F_Text_SamuelDefeat
# 7 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_SamuelPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 9 "data/maps/VictoryRoad_B1F/scripts.pory"

# 10 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Shannon::
# 11 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SHANNON, VictoryRoad_B1F_Text_ShannonIntro, VictoryRoad_B1F_Text_ShannonDefeat
# 12 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_ShannonPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 14 "data/maps/VictoryRoad_B1F/scripts.pory"

# 15 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Michelle::
# 16 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MICHELLE, VictoryRoad_B1F_Text_MichelleIntro, VictoryRoad_B1F_Text_MichelleDefeat
# 17 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MichellePostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 19 "data/maps/VictoryRoad_B1F/scripts.pory"

# 20 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Mitchell::
# 21 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MITCHELL, VictoryRoad_B1F_Text_MitchellIntro, VictoryRoad_B1F_Text_MitchellDefeat
# 22 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MitchellPostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 24 "data/maps/VictoryRoad_B1F/scripts.pory"

# 25 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Halle::
# 26 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_HALLE, VictoryRoad_B1F_Text_HalleIntro, VictoryRoad_B1F_Text_HalleDefeat
# 27 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_HallePostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 29 "data/maps/VictoryRoad_B1F/scripts.pory"

# 30 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelIntro:
# 31 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Pensar que estoy cada vez más cerca\n"
# 32 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "de la LIGA POKéMON…\p"
# 33 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Me entra miedo escénico…$"
# 34 "data/maps/VictoryRoad_B1F/scripts.pory"

# 35 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelDefeat:
# 36 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "No me he dado ni cuenta…$"
# 37 "data/maps/VictoryRoad_B1F/scripts.pory"

# 38 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelPostBattle:
# 39 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "La LIGA POKéMON vuelve a estar\n"
# 40 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "lejos, lejos… Qué depresión…$"
# 41 "data/maps/VictoryRoad_B1F/scripts.pory"

# 42 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonIntro:
# 43 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Para ganar en la LIGA POKéMON, debes\n"
# 44 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "contar con la confianza de tus POKéMON.$"
# 45 "data/maps/VictoryRoad_B1F/scripts.pory"

# 46 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonDefeat:
# 47 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Se nota que vuestra relación se basa\n"
# 48 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "en la mutua confianza.$"
# 49 "data/maps/VictoryRoad_B1F/scripts.pory"

# 50 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonPostBattle:
# 51 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Cuanto más tiempo pasan juntos,\n"
# 52 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "más crece la confianza entre POKéMON\l"
# 53 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "y ENTRENADORES.$"
# 54 "data/maps/VictoryRoad_B1F/scripts.pory"

# 55 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleIntro:
# 56 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Éste no es el objetivo final, sólo\n"
# 57 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "un paso más hacia la LIGA POKéMON.$"
# 58 "data/maps/VictoryRoad_B1F/scripts.pory"

# 59 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleDefeat:
# 60 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Tú avanzas rápido!$"
# 61 "data/maps/VictoryRoad_B1F/scripts.pory"

# 62 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichellePostBattle:
# 63 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Seguro que lo haces muy bien!\n"
# 64 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Tus POKéMON parecen emocionados!$"
# 65 "data/maps/VictoryRoad_B1F/scripts.pory"

# 66 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellIntro:
# 67 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Mis POKéMON provocan una\n"
# 68 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "admiración galáctica!$"
# 69 "data/maps/VictoryRoad_B1F/scripts.pory"

# 70 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellDefeat:
# 71 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Nunca había conocido a nadie igual.$"
# 72 "data/maps/VictoryRoad_B1F/scripts.pory"

# 73 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellPostBattle:
# 74 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "De ti y de tus POKéMON emana\n"
# 75 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "un poder cósmico sin igual,\l"
# 76 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "incluso cuando no lucháis.$"
# 77 "data/maps/VictoryRoad_B1F/scripts.pory"

# 78 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleIntro:
# 79 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Eh, tranqui, no te mosquees!\n"
# 80 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Vamos a luchar con calma!$"
# 81 "data/maps/VictoryRoad_B1F/scripts.pory"

# 82 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleDefeat:
# 83 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Guau!\n"
# 84 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Ha sido magnífico!$"
# 85 "data/maps/VictoryRoad_B1F/scripts.pory"

# 86 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HallePostBattle:
# 87 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Estamos en la CALLE VICTORIA.\p"
# 88 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Pero en el fondo no es tan distinta\n"
# 89 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "de cualquier otra ruta.\p"
# 90 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "¡Intenta disfrutar de todo\n"
# 91 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "lo que te queda por ver!$"
