# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House1/scripts.pory"

# 5 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 6 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House1/scripts.pory"

# 9 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 10 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Cuando empieza un combate POKéMON,\n"
# 11 "data/maps/OldaleTown_House1/scripts.pory"
	.string "el que está a la izquierda de la lista\l"
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.string "sale a luchar primero.\p"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
	.string "Así que, cuando tengas varios POKéMON\n"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
	.string "en tu equipo, prueba a cambiar el orden.\p"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	.string "En algunos casos, podría darte ventaja.$"
