# 1 "data/maps/AquaHideout_UnusedRubyMap2/TrainerHill_4F/scripts.pory"

# 2 "data/maps/AquaHideout_UnusedRubyMap2/TrainerHill_4F/scripts.pory"
TrainerHill_4F_MapScripts::
# 3 "data/maps/AquaHideout_UnusedRubyMap2/TrainerHill_4F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerHill_OnResume
# 4 "data/maps/AquaHideout_UnusedRubyMap2/TrainerHill_4F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerHill_OnFrame
# 5 "data/maps/AquaHideout_UnusedRubyMap2/TrainerHill_4F/scripts.pory"
	.byte 0
