PasswordAshSM1::
# 2 "data/scripts/password_system.pory"
	lockall
# 3 "data/scripts/password_system.pory"
	setflag FLAG_ASHS_POKEMON
# 5 "data/scripts/password_system.pory"
	givemon SPECIES_PIKACHU_ALOLA, 85, ITEM_PIKASHUNIUM_Z, ITEM_POKE_BALL, NATURE_BRAVE, 1, 0, 0, 0, 0, 63, 63, 1, 7, 7, 7, 7, 7, 7, MOVE_QUICK_ATTACK, MOVE_THUNDERBOLT, MOVE_IRON_TAIL, MOVE_ELECTROWEB, FALSE
# 6 "data/scripts/password_system.pory"
	givemon SPECIES_ROWLET, 85, ITEM_EVERSTONE, ITEM_POKE_BALL, NATURE_JOLLY, 2, 0, 0, 1, 0, 63, 63, 0, 7, 7, 7, 7, 7, 7, MOVE_RAZOR_LEAF, MOVE_SEED_BOMB, MOVE_BRAVE_BIRD, MOVE_FEATHER_DANCE, FALSE
# 7 "data/scripts/password_system.pory"
	givemon SPECIES_LYCANROC_DUSK, 85, ITEM_LYCANIUM_Z, ITEM_POKE_BALL, NATURE_ADAMANT, 0, 1, 0, 63, 1, 63, 0, 0, 7, 7, 7, 7, 7, 7, MOVE_STONE_EDGE, MOVE_ACCELEROCK, MOVE_CRUNCH, MOVE_COUNTER, FALSE
# 8 "data/scripts/password_system.pory"
	givemon SPECIES_INCINEROAR, 85, ITEM_FIRIUM_Z, ITEM_POKE_BALL, NATURE_RASH, 1, 0, 1, 63, 0, 0, 63, 0, 7, 7, 7, 7, 7, 7, MOVE_DARKEST_LARIAT, MOVE_FIRE_FANG, MOVE_FIRE_BLAST, MOVE_REVENGE, FALSE
# 9 "data/scripts/password_system.pory"
	givemon SPECIES_NAGANADEL, 85, ITEM_ELECTRIUM_Z, ITEM_BEAST_BALL, NATURE_NAIVE, 0, 1, 0, 63, 0, 63, 1, 0, 7, 7, 7, 7, 7, 7, MOVE_THUNDERBOLT, MOVE_X_SCISSOR, MOVE_SLUDGE_BOMB, MOVE_DRAGON_PULSE, FALSE
# 10 "data/scripts/password_system.pory"
	givemon SPECIES_MELMETAL, 85, ITEM_ELECTRIUM_Z, ITEM_POKE_BALL, NATURE_BRAVE, 1, 0, 1, 63, 63, 0, 0, 0, 7, 7, 7, 7, 7, 7, MOVE_DISCHARGE, MOVE_DOUBLE_IRON_BASH, MOVE_FLASH_CANNON, MOVE_ICE_PUNCH, TRUE
# 11 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_TMHM
# 12 "data/scripts/password_system.pory"
	msgbox PasswordAsh_Text
# 13 "data/scripts/password_system.pory"
	clearflag FLAG_ASHS_POKEMON
# 14 "data/scripts/password_system.pory"
	releaseall
	end


PasswordAshSM2::
# 19 "data/scripts/password_system.pory"
	lockall
# 20 "data/scripts/password_system.pory"
	setflag FLAG_ASHS_POKEMON
# 21 "data/scripts/password_system.pory"
	givemon SPECIES_PIKACHU_ALOLA, 15, ITEM_PIKASHUNIUM_Z, ITEM_POKE_BALL, NATURE_BRAVE, 1, 0, 0, 0, 0, 63, 63, 1, 7, 7, 7, 7, 7, 7, MOVE_QUICK_ATTACK, MOVE_THUNDERBOLT, MOVE_IRON_TAIL, MOVE_ELECTROWEB, FALSE
# 22 "data/scripts/password_system.pory"
	givemon SPECIES_ROWLET, 15, ITEM_EVERSTONE, ITEM_POKE_BALL, NATURE_JOLLY, 2, 0, 0, 1, 0, 63, 63, 0, 7, 7, 7, 7, 7, 7, MOVE_RAZOR_LEAF, MOVE_SEED_BOMB, MOVE_BRAVE_BIRD, MOVE_FEATHER_DANCE, FALSE
# 23 "data/scripts/password_system.pory"
	givemon SPECIES_ROCKRUFF_OWN_TEMPO, 15, ITEM_LYCANIUM_Z, ITEM_POKE_BALL, NATURE_ADAMANT, 1, 0, 0, 63, 1, 63, 0, 0, 7, 7, 7, 7, 7, 7, MOVE_STONE_EDGE, MOVE_ACCELEROCK, MOVE_CRUNCH, MOVE_COUNTER, FALSE
# 24 "data/scripts/password_system.pory"
	givemon SPECIES_LITTEN, 15, ITEM_FIRIUM_Z, ITEM_POKE_BALL, NATURE_RASH, 1, 0, 1, 63, 0, 0, 63, 0, 7, 7, 7, 7, 7, 7, MOVE_DARKEST_LARIAT, MOVE_FIRE_FANG, MOVE_FIRE_BLAST, MOVE_REVENGE, FALSE
# 25 "data/scripts/password_system.pory"
	givemon SPECIES_POIPOLE, 15, ITEM_ELECTRIUM_Z, ITEM_BEAST_BALL, NATURE_NAIVE, 1, 0, 0, 63, 0, 63, 1, 0, 7, 7, 7, 7, 7, 7, MOVE_THUNDERBOLT, MOVE_X_SCISSOR, MOVE_SLUDGE_BOMB, MOVE_DRAGON_PULSE, FALSE
# 26 "data/scripts/password_system.pory"
	givemon SPECIES_MELTAN, 15, ITEM_ELECTRIUM_Z, ITEM_POKE_BALL, NATURE_BRAVE, 1, 0, 1, 63, 63, 0, 0, 0, 7, 7, 7, 7, 7, 7, MOVE_DISCHARGE, MOVE_DOUBLE_IRON_BASH, MOVE_FLASH_CANNON, MOVE_ICE_PUNCH, TRUE
# 27 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_TMHM
# 28 "data/scripts/password_system.pory"
	msgbox PasswordAsh_Text2
# 29 "data/scripts/password_system.pory"
	clearflag FLAG_ASHS_POKEMON
# 30 "data/scripts/password_system.pory"
	releaseall
	end


# 33 "data/scripts/password_system.pory"

# 34 "data/scripts/password_system.pory"
Password1::
# 35 "data/scripts/password_system.pory"
	lockall
# 36 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_ITEM
# 37 "data/scripts/password_system.pory"
    msgbox Password1_Text, 2
# 38 "data/scripts/password_system.pory"
	release
# 39 "data/scripts/password_system.pory"
    end
# 40 "data/scripts/password_system.pory"

# 41 "data/scripts/password_system.pory"
Password2::
# 42 "data/scripts/password_system.pory"
	lockall
# 43 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_ITEM
# 44 "data/scripts/password_system.pory"
    msgbox Password2_Text, 2
# 45 "data/scripts/password_system.pory"
	release
# 46 "data/scripts/password_system.pory"
	end
# 47 "data/scripts/password_system.pory"

# 48 "data/scripts/password_system.pory"
Password3::
# 49 "data/scripts/password_system.pory"
	lockall
# 50 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_ITEM
# 51 "data/scripts/password_system.pory"
    msgbox Password3_Text, 2
# 52 "data/scripts/password_system.pory"
	release
# 53 "data/scripts/password_system.pory"
	end
# 54 "data/scripts/password_system.pory"

# 55 "data/scripts/password_system.pory"
PasswordMuchos::
# 56 "data/scripts/password_system.pory"
	lockall
# 57 "data/scripts/password_system.pory"
	playfanfare MUS_OBTAIN_ITEM
# 58 "data/scripts/password_system.pory"
    msgbox PasswordMuchos_Text, 2
# 59 "data/scripts/password_system.pory"
	waitmessage
# 60 "data/scripts/password_system.pory"
	release
# 61 "data/scripts/password_system.pory"
	end
# 62 "data/scripts/password_system.pory"
PasswordFallo::
# 63 "data/scripts/password_system.pory"
	lockall
# 64 "data/scripts/password_system.pory"
	playse SE_FAILURE
# 65 "data/scripts/password_system.pory"
    msgbox PasswordIncorrecta_Text, 2
# 66 "data/scripts/password_system.pory"
	waitmessage
# 67 "data/scripts/password_system.pory"
	release
# 68 "data/scripts/password_system.pory"
	end
# 69 "data/scripts/password_system.pory"

# 70 "data/scripts/password_system.pory"
PasswordEvento1::
# 71 "data/scripts/password_system.pory"
	lockall
# 72 "data/scripts/password_system.pory"
	msgbox TextoEvento1
# 73 "data/scripts/password_system.pory"
	releaseall
# 74 "data/scripts/password_system.pory"
	return
# 75 "data/scripts/password_system.pory"

# 76 "data/scripts/password_system.pory"

# 77 "data/scripts/password_system.pory"

# 78 "data/scripts/password_system.pory"

# 79 "data/scripts/password_system.pory"
TextoEvento1:
# 80 "data/scripts/password_system.pory"
	.string "¡Oh, algo te indica que algo cambió en la\n"
# 81 "data/scripts/password_system.pory"
	.string "Ruta 101!\p"
# 82 "data/scripts/password_system.pory"
	.string "¡Ve para ahí!$"
# 83 "data/scripts/password_system.pory"
 
# 84 "data/scripts/password_system.pory"
 
# 85 "data/scripts/password_system.pory"
Password1_Text::
# 86 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\p¡Recibiste {STR_VAR_1}!.$"
# 87 "data/scripts/password_system.pory"
Password2_Text::
# 88 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\p¡Recibiste {STR_VAR_1}\ny {STR_VAR_2}!$"
# 89 "data/scripts/password_system.pory"
Password3_Text::
# 90 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\p¡Recibiste {STR_VAR_1}, \n{STR_VAR_2} y {STR_VAR_3}!$"
# 91 "data/scripts/password_system.pory"
PasswordMuchos_Text::
# 92 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\n¡Recibiste muchas cosas!$"
# 93 "data/scripts/password_system.pory"
PasswordRecibiste_Text::
# 94 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!$"
# 95 "data/scripts/password_system.pory"
PasswordIncorrecta_Text::
# 96 "data/scripts/password_system.pory"
	.string "Contraseña incorrecta.$"
# 97 "data/scripts/password_system.pory"
PasswordAsh_Text::
# 98 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\p¡Oh!\n¡Parece que proviene del Anime!\p¡Ahora tienes los Pokémon que Ash\nKetchum usó en la Región {STR_VAR_1}!$"
# 99 "data/scripts/password_system.pory"

# 100 "data/scripts/password_system.pory"
PasswordAsh_Text2::
# 101 "data/scripts/password_system.pory"
	.string "¡Te han enviado un Regalo Misterioso!\p¡Oh!\n¡Parece que proviene del Anime!\p¡Ahora tienes los Pokémon que Ash\nKetchum usó en la Región {STR_VAR_1},\llistos para usar!$"
