# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts::
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM::
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl::
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains:
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "Mi POKéMON tiene una naturaleza\n"
# 15 "data/maps/SlateportCity_House/scripts.pory"
	.string "ACTIVA.\p"
# 16 "data/maps/SlateportCity_House/scripts.pory"
	.string "Comparado con otros POKéMON,\n"
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "su VELOCIDAD es mayor.\p"
# 18 "data/maps/SlateportCity_House/scripts.pory"
	.string "Quizás la naturaleza de los POKéMON\n"
# 19 "data/maps/SlateportCity_House/scripts.pory"
	.string "esté relacionada con cómo mejoran\l"
# 20 "data/maps/SlateportCity_House/scripts.pory"
	.string "algunas habilidades más que otras.$"
# 21 "data/maps/SlateportCity_House/scripts.pory"

# 22 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent:
# 23 "data/maps/SlateportCity_House/scripts.pory"
	.string "Tú entrenas POKéMON, ¿a que sí?\p"
# 24 "data/maps/SlateportCity_House/scripts.pory"
	.string "Ya que estás en CIUDAD PORTUAL, no\n"
# 25 "data/maps/SlateportCity_House/scripts.pory"
	.string "te puedes perder la TIENDA de BATALLA.$"
