# 1 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 2 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_MapScripts::
# 3 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 5 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
# 6 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
# 7 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	end
# 8 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 9 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
# 10 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
# 11 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	end
# 12 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 13 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
# 14 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Diseñar un gran barco se parece\n"
# 15 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "más a construir un edificio que\l"
# 16 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "a crear un medio de transporte.$"
# 17 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"

# 18 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
# 19 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "¿No te parece extraño que un barco\n"
# 20 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "construido con hierro pueda flotar?\p"
# 21 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Pues bien, flota gracias al principio\n"
# 22 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "de la flotabilidad. ¡Naturalmente!$"
