# 1 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 2 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_MapScripts::
# 3 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 5 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Andrea::
# 6 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
# 7 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 9 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 10 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Crissy::
# 11 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
# 12 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 14 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 15 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Brianna::
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
# 17 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
# 18 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 19 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Connie::
# 21 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
# 22 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
# 23 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 24 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 25 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bridget::
# 26 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
# 27 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
# 28 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 29 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 30 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Olivia::
# 31 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
# 32 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
# 33 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 34 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 35 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Tiffany::
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
# 37 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
# 38 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 39 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Bethany::
# 41 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
# 42 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 44 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 45 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Annika::
# 46 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
# 47 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
# 48 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 49 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 50 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_EventScript_Daphne::
# 51 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
# 52 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
# 53 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	end
# 54 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 55 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaIntro:
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Te voy a enseñar una muestra de todo\n"
# 57 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "lo que he aprendido con GALANO.$"
# 58 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 59 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaDefeat:
# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "GALANO no va a estar contento…$"
# 61 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 62 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
# 63 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Te sugiero que intentes caminar sobre\n"
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "todas las baldosas. Pero sobre toditas,\l"
# 65 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "todas. Podría pasar algo interesante…$"
# 66 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 67 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyIntro:
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Has venido desde muy lejos, pero no\n"
# 69 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "creas que llegarás hasta GALANO.\p"
# 70 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡No si depende de mí!$"
# 71 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyDefeat:
# 73 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡Qué fuerte eres!\n"
# 74 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Me he dejado engañar por tu aspecto…$"
# 75 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
# 77 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Puede que tú sí seas capaz\n"
# 78 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "de poner a GALANO en un brete.$"
# 79 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneIntro:
# 81 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ver a GALANO en acción\n"
# 82 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "es todo un espectáculo.\p"
# 83 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "De hecho, es lo que me dio ganas\n"
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "de llegar a ser una ENTRENADORA.$"
# 85 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 86 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphneDefeat:
# 87 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Has luchado con mucha más gracia\n"
# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "y elegancia que yo…$"
# 89 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 90 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
# 91 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Tu estilo combatiendo es inigualable.\p"
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Y yo soy tan feliz de poder disfrutar\n"
# 93 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "de la belleza de los POKéMON…$"
# 94 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 95 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieIntro:
# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Vas a aprender lo duro que puede\n"
# 97 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "ser un combate…$"
# 98 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 99 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConnieDefeat:
# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ejem…\n"
# 101 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Más bien lo he aprendido yo…$"
# 102 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 103 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_ConniePostBattle:
# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Te voy a decir algo…\p"
# 105 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Si quieres llegar hasta GALANO, debes\n"
# 106 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "caminar sobre cada baldosa de la sala,\l"
# 107 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "pero sólo una vez sobre cada una.$"
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 109 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetIntro:
# 110 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "El GIMNASIO POKéMON de mayor nivel\n"
# 111 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "en toda la región de HOENN es…\p"
# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡el GIMNASIO de ARRECÍPOLIS!$"
# 113 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 114 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetDefeat:
# 115 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡Tu nivel de combate es superior!$"
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 117 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
# 118 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Yo creo que no hay que anclarse\n"
# 119 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "en ningún GIMNASIO, aunque sea bueno.\p"
# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Se mejora mucho más entrenando\n"
# 121 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "en varios sitios. ¡Y es más divertido!$"
# 122 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 123 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaIntro:
# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Entreno mis POKéMON con GALANO.\p"
# 125 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡No será tan fácil vencerme!$"
# 126 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 127 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaDefeat:
# 128 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Me han derrotado…$"
# 129 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 130 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
# 131 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Creo que tienes potencial.\n"
# 132 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¿Por qué no te quedas a entrenar\l"
# 133 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "en este GIMNASIO?$"
# 134 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 135 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyIntro:
# 136 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¿Imaginas deslizarte grácilmente\n"
# 137 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "por el hielo sin caer ni una vez?\p"
# 138 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡Un ENTRENADOR capaz de hacer\n"
# 139 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "eso es el colmo de la elegancia!$"
# 140 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 141 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
# 142 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Eh… ¿Qué ha pasado aquí?$"
# 143 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 144 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
# 145 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Voy a decir una perogrullada, pero está\n"
# 146 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "claro que ganar o perder no depende\l"
# 147 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "de la edad… Y ése es tu caso.$"
# 148 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 149 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyIntro:
# 150 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Cuando estoy con mis POKéMON,\n"
# 151 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "el tiempo pasa en un “plisplás”.$"
# 152 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 153 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyDefeat:
# 154 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Me has dejado “plisplada”.$"
# 155 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 156 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
# 157 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Espero que este incidente no me haga\n"
# 158 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "olvidar que la vida es “plisplante”.$"
# 159 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 160 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaIntro:
# 161 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Si lo prefieres, puedo usar POKéMON\n"
# 162 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "muy, pero que muy raros en combate.$"
# 163 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 164 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
# 165 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "¡Pues vaya! ¿Pero has podido echar\n"
# 166 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "un buen vistazo a mis POKéMON?$"
# 167 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 168 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
# 169 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Vine a este GIMNASIO porque GALANO\n"
# 170 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "alabó encarecidamente a mis POKéMON.\p"
# 171 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, ojalá hubiera conocido a GALANO\n"
# 172 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "hace años, cuando era joven…$"
# 173 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 174 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaIntro:
# 175 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Ji, ji, ji…\n"
# 176 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Tienes un encanto especial.$"
# 177 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 178 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaDefeat:
# 179 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Qué mal…\n"
# 180 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Te lo he puesto muy fácil.$"
# 181 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"

# 182 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
# 183 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Estoy segura de que GALANO no dejará\n"
# 184 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "que le pongas un dedo encima. Ji, ji…$"
