# 1 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 2 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_MapScripts::
# 3 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.byte 0
# 4 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 5 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_EventScript_Grunt9::
# 6 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_Text_Grunt9Intro, MagmaHideout_3F_1R_Text_Grunt9Defeat
# 7 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt9PostBattle, MSGBOX_AUTOCLOSE
# 8 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	end
# 9 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 10 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_EventScript_Grunt16::
# 11 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_single TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_Text_Grunt16Intro, MagmaHideout_3F_1R_Text_Grunt16Defeat
# 12 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt16PostBattle, MSGBOX_AUTOCLOSE
# 13 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	end
# 14 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 15 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9Intro:
# 16 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¿Qué he hecho yo para merecer\n"
# 17 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "este puesto de guardia?\p"
# 18 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡Tengo las orejas ardiendo!$"
# 19 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 20 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9Defeat:
# 21 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "El calor me da flojera…$"
# 22 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 23 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt9PostBattle:
# 24 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¿Te parece raro que llevemos capuchas\n"
# 25 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "en un volcán lleno de lava como éste?$"
# 26 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 27 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16Intro:
# 28 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Nos unimos al EQUIPO MAGMA para ayudar\n"
# 29 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "a nuestro líder a cumplir su visión.\p"
# 30 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Me da igual si eres del EQUIPO AQUA\n"
# 31 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "o sólo estás de paso por aquí.\p"
# 32 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡Nadie interfiere en nuestros planes\n"
# 33 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "y se sale con la suya!$"
# 34 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 35 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16Defeat:
# 36 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡Oh, no!\n"
# 37 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡Esto no es de recibo!$"
# 38 "data/maps/MagmaHideout_3F_1R/scripts.pory"

# 39 "data/maps/MagmaHideout_3F_1R/scripts.pory"
MagmaHideout_3F_1R_Text_Grunt16PostBattle:
# 40 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Escúchame bien.\n"
# 41 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡El EQUIPO MAGMA tiene razón!\p"
# 42 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "No hagas ni caso al EQUIPO AQUA.\n"
# 43 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "¡Mienten más que hablan!$"
