# 1 "data/maps/LilycoveCity_House4/scripts.pory"

# 2 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_MapScripts::
# 3 "data/maps/LilycoveCity_House4/scripts.pory"
	.byte 0
# 4 "data/maps/LilycoveCity_House4/scripts.pory"

# 5 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man1::
# 6 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
# 7 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 8 "data/maps/LilycoveCity_House4/scripts.pory"

# 9 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_EventScript_Man2::
# 10 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
# 11 "data/maps/LilycoveCity_House4/scripts.pory"
	end
# 12 "data/maps/LilycoveCity_House4/scripts.pory"

# 13 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
# 14 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "“Los mayores misterios de nuestro\n"
# 15 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "planeta están en el fondo del mar.”\p"
# 16 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "No me acuerdo de quién dijo eso…$"
# 17 "data/maps/LilycoveCity_House4/scripts.pory"

# 18 "data/maps/LilycoveCity_House4/scripts.pory"
LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
# 19 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Hay una gran zanja submarina entre\n"
# 20 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "ALGARIA y ARRECÍPOLIS.\p"
# 21 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "Al menos eso tengo entendido…$"
